### ISSUE TITLE
ActivityToast窗体泄漏

### ISSUE THREAD

**Issue by Wensibob** [Dovar66/DovaToast#7]
ActivityToast显示时，如果快速按返回键返回上个页面，这个时候Toast会闪一下，控制台日志如下：
```
01-28 14:28:12.808 539-539/com.dovar.dtoast E/WindowManager: android.view.WindowLeaked: Activity com.dovar.dovatoast.SecondActivity has leaked window android.widget.RelativeLayout{2d488bc V.E...... ......ID 0,0-311,103} that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:505)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at com.dovar.dtoast.inner.DovaTN.displayToast(DovaTN.java:194)
        at com.dovar.dtoast.inner.DovaTN.showNextToast(DovaTN.java:156)
        at com.dovar.dtoast.inner.DovaTN.notifyNewToastComeIn(DovaTN.java:90)
        at com.dovar.dtoast.inner.DovaTN.add(DovaTN.java:55)
        at com.dovar.dtoast.inner.DovaToast.show(DovaToast.java:72)
        at com.dovar.dovatoast.ToastUtil.show(ToastUtil.java:27)
        at com.dovar.dovatoast.SecondActivity.onClick(SecondActivity.java:30)
        at java.lang.reflect.Method.invoke(Native Method)
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
        at android.view.View.performClick(View.java:6303)
        at android.view.View$PerformClick.run(View.java:24828)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6809)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by Dovar66** [comment]
已提交修复https://github.com/Dovar66/DToast/commit/9f289a95e27dc661f5dd740660af0cd984a0ee2f
